import json
import re
import os
from typing import Dict, Any, List
from utils.llm import call_gemini, is_gemini_available
from agents.fix_generation.prompts import (
    FIX_GENERATION_SYSTEM_PROMPT, FIX_GENERATION_USER_PROMPT,
    FULL_FILE_FIX_SYSTEM_PROMPT, FULL_FILE_FIX_USER_PROMPT,
)
from agents.fix_generation.python_repair import repair_python_code, run_python_file

LLM_FIX_ROUNDS = 5


def _parse_llm_fix(raw: str) -> Dict[str, Any]:
    """Extract {"explanation", "fixed_code"} from a Gemini reply (JSON, or a fenced code block)."""
    if not raw:
        return None
    text = raw.strip()
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        try:
            parsed = json.loads(m.group(0))
            if parsed.get("fixed_code"):
                code = parsed["fixed_code"]
                fence = re.match(r"^```\w*\n(.*?)\n?```\s*$", code.strip(), re.DOTALL)
                parsed["fixed_code"] = fence.group(1) if fence else code
                return parsed
        except Exception:
            pass
    fence = re.search(r"```\w*\n(.*?)```", text, re.DOTALL)
    if fence:
        return {"explanation": "Fix generated by Gemini.", "fixed_code": fence.group(1)}
    return None


def _strip_comments(code: str) -> str:
    return "\n".join(re.sub(r"\s*#.*$", "", l).rstrip() for l in code.splitlines() if l.strip() and not l.strip().startswith("#"))


def _wraps_errors(candidate: str, original: str) -> bool:
    """True if the candidate hides errors: a top-level try wrapper, or new bare/broad excepts that just swallow."""
    first = next((l for l in candidate.splitlines() if l.strip() and not l.strip().startswith("#")), "")
    if first.startswith("try:"):
        return True
    swallow = r"except\s*(Exception)?\s*(as\s+\w+)?\s*:\s*\n\s*(pass|print\(|continue|return None)"
    return len(re.findall(swallow, candidate)) > len(re.findall(swallow, original))


def _llm_full_file_fix(code: str, target_file: str, language: str, error_output: str,
                       root_cause: Dict[str, Any], project_path: str, feedback: str) -> Dict[str, Any]:
    """
    Ask Gemini for the complete corrected file. For Python, run each candidate and feed any
    new error back to Gemini for up to LLM_FIX_ROUNDS rounds; finish with the rule-based
    repair loop if something is still left. Returns None if Gemini gave nothing usable.
    """
    is_python = language == "python"
    history: List[str] = [feedback] if feedback else []
    explanations: List[str] = []
    current, output, best = code, error_output or "Program exited with an error.", None

    for round_no in range(1, LLM_FIX_ROUNDS + 1):
        prompt = FULL_FILE_FIX_USER_PROMPT.format(
            filename=target_file, language=language, source_code=current,
            error_output=(output or "")[-4000:],
            root_cause=json.dumps(root_cause or {}, indent=2)[:2000],
            history="\n".join(history) or "None (first attempt)",
        )
        parsed = _parse_llm_fix(call_gemini(prompt, FULL_FILE_FIX_SYSTEM_PROMPT.format(language=language)))
        if not parsed:
            break  # Gemini unavailable or unusable reply
        candidate = parsed["fixed_code"]

        if not is_python:
            best = candidate
            explanations.append(parsed.get("explanation", ""))
            break  # Java is compiled/run by the testing agent; the supervisor loop retries

        if not _compiles(candidate):
            history.append(f"Attempt {round_no}: your code did not compile. Return valid Python.")
            continue
        if _wraps_errors(candidate, current):
            history.append(f"Attempt {round_no}: you hid errors with try/except instead of fixing the cause. Fix the actual bug.")
            continue
        if _strip_comments(candidate) == _strip_comments(current) and round_no == 1:
            history.append(f"Attempt {round_no}: you only changed comments/whitespace. Fix the actual code.")
            continue

        explanations.append(str(parsed.get("explanation", "")).strip())
        current = best = candidate
        try:
            proc = run_python_file(candidate, target_file, project_path)
        except Exception as e:
            output = f"Execution failed: {e}"
            history.append(f"Attempt {round_no}: {output}")
            continue
        if proc.returncode == 0:
            break
        output = (proc.stdout + "\n" + proc.stderr).strip()
        history.append(f"Attempt {round_no}: still failing with:\n{output[-1500:]}")

    if best is None:
        return None

    explanation = "\n".join(e for e in explanations if e) or "Fix generated by Gemini."
    if is_python:
        # Rule-based loop as a safety net for anything Gemini left behind
        repaired = repair_python_code(best, target_file, project_path)
        if repaired["notes"]:
            explanation += "\nAutomated repair: " + " ".join(repaired["notes"])
        best = repaired["fixed_code"]

    return {
        "explanation": explanation,
        "fixed_code": best,
        "changed_section": explanation,
        "patches": [{"file": target_file, "changes": best, "reason": explanation}],
        "engine": "gemini",
    }


def _resolve_target_file(state: Dict[str, Any], code_analysis: Dict[str, Any]) -> str:
    """Pick the file the fix should be written to: the uploaded file if it exists in the workspace."""
    project_path = state.get("project_path")
    project_name = state.get("project_name")
    if project_name and project_path and os.path.isfile(os.path.join(project_path, project_name)):
        return project_name
    files = (code_analysis.get("source_files") or []) + (code_analysis.get("test_files") or [])
    if files:
        return files[0]
    return project_name or "main.py"


def _compiles(code: str) -> bool:
    try:
        compile(code, "<fix>", "exec")
        return True
    except SyntaxError:
        return False


def _python_repair_fix(code: str, target_file: str, project_path: str, base: Dict[str, Any] = None) -> Dict[str, Any]:
    """Run the compile-and-run repair loop and package the result as a candidate fix."""
    repaired = repair_python_code(code, target_file, project_path)
    if not repaired["notes"] and base is None:
        return None
    explanation = (base or {}).get("explanation", "")
    if repaired["notes"]:
        explanation = (explanation + "\n" if explanation else "") + "Automated repair: " + " ".join(repaired["notes"])
    fixed_code = repaired["fixed_code"]
    return {
        "explanation": explanation or "Validated fix.",
        "fixed_code": fixed_code,
        "changed_section": "\n".join(f"+ {n}" for n in repaired["notes"]) or (base or {}).get("changed_section", ""),
        "patches": [{"file": target_file, "changes": fixed_code, "reason": explanation}],
        "repair_complete": repaired["runs_clean"],
    }

def fallback_fix_generation(
    source_code: str,
    error_log: str,
    root_cause: Dict[str, Any],
    code_analysis: Dict[str, Any] = None
) -> Dict[str, Any]:
    """
    Rule-based fallback fix generator for standard python and java errors.
    """
    category = root_cause.get("bug_category", "")
    code_analysis = code_analysis or {}
    snippets = code_analysis.get("snippets", {})

    src_files = code_analysis.get("source_files", [])
    py_file = src_files[0] if src_files else (list(snippets.keys())[0] if snippets else "main.py")
    java_file = src_files[0] if src_files else (list(snippets.keys())[0] if snippets else "UserService.java")

    # Check Java NullPointerException
    if "NullPointerException" in error_log or category == "NullPointerException":
        if snippets and java_file in snippets:
            source_code = snippets[java_file]

        if "user.getName()" in source_code or "user == null" not in source_code:
            fixed_code = source_code.replace(
                "return user.getName();",
                "if (user == null) {\n            return \"Guest\";\n        }\n        return user.getName();"
            )
            if fixed_code == source_code:
                # General null check substitution
                fixed_code = re.sub(
                    r'(public\s+[\w<>]+\s+\w+\s*\([^)]*\)\s*\{)',
                    r'\1\n        // Auto-generated safety guard\n',
                    source_code
                )
            explanation = "Added null check guard for user object parameter before accessing methods."
            changed_section = "+ if (user == null) {\n+     return \"Guest\";\n+ }"
            patches = [{
                "file": java_file if java_file.endswith(".java") else "UserService.java",
                "changes": fixed_code,
                "reason": explanation
            }]
            return {
                "explanation": explanation,
                "fixed_code": fixed_code,
                "changed_section": changed_section,
                "patches": patches
            }

    # Python error fixes
    if "ZeroDivisionError" in error_log or category == "ZeroDivisionError":
        if snippets and py_file in snippets:
            source_code = snippets[py_file]

        if "return total / count" in source_code:
            fixed_code = source_code.replace(
                "return total / count",
                "if not numbers or count == 0:\n        return 0.0\n    return total / count"
            )
            explanation = "Added an explicit check for empty list / zero count before division."
            changed_section = "+ if not numbers or count == 0:\n+     return 0.0"
        else:
            lines = source_code.splitlines()
            fixed_lines = []
            for line in lines:
                if "/" in line and not line.strip().startswith("#"):
                    indent = len(line) - len(line.lstrip())
                    ind = " " * indent
                    fixed_lines.append(f"{ind}if len(numbers) == 0:\n{ind}    return 0.0")
                fixed_lines.append(line)
            fixed_code = "\n".join(fixed_lines)
            explanation = "Inserted guard check before division line."
            changed_section = "+ Guard clause added before division."

        patches = [{
            "file": py_file,
            "changes": fixed_code,
            "reason": explanation
        }]
        return {
            "explanation": explanation,
            "fixed_code": fixed_code,
            "changed_section": changed_section,
            "patches": patches
        }

    elif "IndexError" in error_log or category == "IndexError":
        if snippets and py_file in snippets:
            source_code = snippets[py_file]

        if "return items[2]" in source_code:
            fixed_code = source_code.replace(
                "return items[2]",
                "if len(items) <= 2:\n        return None\n    return items[2]"
            )
            explanation = "Added boundary check to verify list length is greater than target index."
            changed_section = "+ if len(items) <= 2:\n+     return None"
        else:
            fixed_code = source_code.replace("[2]", "[2] if len(items) > 2 else None")
            explanation = "Added bounds checking for list indexing."
            changed_section = "Modified indexing operation with length check."

        patches = [{
            "file": py_file,
            "changes": fixed_code,
            "reason": explanation
        }]
        return {
            "explanation": explanation,
            "fixed_code": fixed_code,
            "changed_section": changed_section,
            "patches": patches
        }

    elif "TypeError" in error_log or category == "TypeError":
        if snippets and py_file in snippets:
            source_code = snippets[py_file]

        fixed_code = source_code.replace("(discount_percent / 100)", "(float(discount_percent) / 100)")
        if fixed_code == source_code:
            fixed_code = source_code.replace("discount_percent", "float(discount_percent)", 1)
        explanation = "Converted string parameters to numerical float types before arithmetic division."
        changed_section = "+ (float(discount_percent) / 100)"

        patches = [{
            "file": py_file,
            "changes": fixed_code,
            "reason": explanation
        }]
        return {
            "explanation": explanation,
            "fixed_code": fixed_code,
            "changed_section": changed_section,
            "patches": patches
        }

    elif "KeyError" in error_log or category == "KeyError":
        if snippets and py_file in snippets:
            source_code = snippets[py_file]

        fixed_code = source_code.replace('user_profile["email"]', 'user_profile.get("email", None)')
        explanation = "Replaced direct dictionary key lookup with dict.get() safe lookup."
        changed_section = "- user_profile[\"email\"]\n+ user_profile.get(\"email\", None)"

        patches = [{
            "file": py_file,
            "changes": fixed_code,
            "reason": explanation
        }]
        return {
            "explanation": explanation,
            "fixed_code": fixed_code,
            "changed_section": changed_section,
            "patches": patches
        }

    elif "NameError" in error_log or category == "NameError":
        name_match = re.search(r"name '([^']+)' is not defined", error_log)
        var_name = name_match.group(1) if name_match else "undefined_var"
        fixed_code = f"{var_name} = None\n" + source_code
        explanation = f"Defined variable '{var_name}' before reference to resolve NameError."
        changed_section = f"+ {var_name} = None"
        patches = [{"file": py_file, "changes": fixed_code, "reason": explanation}]
        return {"explanation": explanation, "fixed_code": fixed_code, "changed_section": changed_section, "patches": patches}

    elif "SyntaxError" in error_log or category == "SyntaxError":
        fixed_code = source_code
        lines = source_code.splitlines()
        fixed_lines = []
        for line in lines:
            if line.strip().startswith("def ") or line.strip().startswith("if ") or line.strip().startswith("else") or line.strip().startswith("for ") or line.strip().startswith("while "):
                if not line.strip().endswith(":"):
                    line = line + ":"
            fixed_lines.append(line)
        fixed_code = "\n".join(fixed_lines)
        explanation = "Corrected missing syntax colon at block statement end."
        changed_section = "+ Added missing syntax colons."
        patches = [{"file": py_file, "changes": fixed_code, "reason": explanation}]
        return {"explanation": explanation, "fixed_code": fixed_code, "changed_section": changed_section, "patches": patches}

    else:
        target_file = py_file if src_files else "main.py"
        # No rule matched. Never hide the error behind a try/except wrapper: leave the code
        # unchanged so verification reports the failure honestly.
        fixed_code = source_code
        explanation = "No automatic fix could be generated for this error (Gemini unavailable and no rule matched)."
        changed_section = "Original code preserved."

        patches = [{
            "file": target_file,
            "changes": fixed_code,
            "reason": explanation
        }]
        return {
            "explanation": explanation,
            "fixed_code": fixed_code,
            "changed_section": changed_section,
            "patches": patches
        }


def generate_fix_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Fix Generation Agent Node for LangGraph.
    Receives state with source_code, root_cause, bug_investigation, and optional verification feedback.
    Returns candidate_fix dict with structured file patches.
    """
    source_code = state.get("source_code", "")
    error_log = state.get("error_log", "")
    root_cause = state.get("root_cause", {})
    bug_investigation = state.get("bug_investigation", {})
    verification_result = state.get("verification_result")
    code_analysis = state.get("code_analysis", {})

    exec_res = state.get("execution_result", {})
    if exec_res and not error_log:
        error_log = exec_res.get("stderr") or exec_res.get("output") or ""

    project_path = state.get("project_path")
    is_python = state.get("language", "python") == "python"
    target_file = _resolve_target_file(state, code_analysis or {})
    python_code = source_code
    if is_python and not python_code and project_path:
        target_path = os.path.join(project_path, target_file)
        if os.path.isfile(target_path):
            with open(target_path, "r", encoding="utf-8") as f:
                python_code = f.read()

    feedback = ""
    if verification_result and not verification_result.get("verified", False):
        feedback = f"Previous fix failed verification: {verification_result.get('reason', 'Tests failed')}"

    language = state.get("language", "python")
    file_code = python_code if is_python else source_code
    if not file_code and project_path and os.path.isfile(os.path.join(project_path, target_file)):
        with open(os.path.join(project_path, target_file), "r", encoding="utf-8") as f:
            file_code = f.read()

    # Primary engine: Gemini repairs the whole file, iterating on real run output
    if is_gemini_available() and file_code:
        latest_output = ((state.get("test_results") or {}).get("output") if verification_result else None) or error_log
        llm_fix = _llm_full_file_fix(file_code, target_file, language, latest_output, root_cause,
                                     project_path, feedback)
        if llm_fix:
            return {"candidate_fix": llm_fix, "patches": llm_fix["patches"]}

    if is_gemini_available() and not file_code:
        user_prompt = FIX_GENERATION_USER_PROMPT.format(
            source_code=source_code if source_code else f"Project snippets: {json.dumps(code_analysis.get('snippets', {}), indent=2)}",
            root_cause=json.dumps(root_cause, indent=2),
            bug_investigation=json.dumps(bug_investigation, indent=2),
            feedback=feedback if feedback else "None (First attempt)"
        )
        raw_response = call_gemini(user_prompt, FIX_GENERATION_SYSTEM_PROMPT)

        if raw_response:
            try:
                cleaned = raw_response.strip()
                json_match = re.search(r'\{.*\}', cleaned, re.DOTALL)
                if json_match:
                    cleaned = json_match.group(0)
                
                parsed = json.loads(cleaned)
                if "fixed_code" in parsed or "patches" in parsed:
                    if "patches" not in parsed or not parsed["patches"]:
                        parsed["patches"] = [{
                            "file": target_file,
                            "changes": parsed.get("fixed_code", source_code),
                            "reason": parsed.get("explanation", "Fix generated by agent")
                        }]
                    # Single-file Python: validate the LLM fix by compiling and running it,
                    # repairing anything it missed. Discard it if it still doesn't parse.
                    if is_python and parsed.get("fixed_code") and len(parsed["patches"]) <= 1:
                        validated = _python_repair_fix(parsed["fixed_code"], target_file, project_path, base=parsed)
                        if _compiles(validated["fixed_code"]):
                            return {"candidate_fix": validated, "patches": validated["patches"]}
                    else:
                        return {
                            "candidate_fix": parsed,
                            "patches": parsed.get("patches", [])
                        }
            except Exception:
                pass

    # Fallback mode: for Python, iteratively compile/run/repair the actual file
    if is_python and python_code:
        repaired = _python_repair_fix(python_code, target_file, project_path)
        if repaired:
            return {"candidate_fix": repaired, "patches": repaired["patches"]}

    result = fallback_fix_generation(source_code, error_log, root_cause, code_analysis)
    if is_python and len(result.get("patches", [])) == 1:
        result["patches"][0]["file"] = target_file
    return {
        "candidate_fix": result,
        "patches": result.get("patches", [])
    }

