import json
import re
import os
from typing import Dict, Any, List
from utils.llm import call_llm, is_llm_available
from agents.fix_generation.prompts import (
    FIX_GENERATION_SYSTEM_PROMPT, FIX_GENERATION_USER_PROMPT,
    FULL_FILE_FIX_SYSTEM_PROMPT, FULL_FILE_FIX_USER_PROMPT,
)
from agents.fix_generation.python_repair import repair_python_code, run_python_file

LLM_FIX_ROUNDS = 5


def _resolve_target_file(state: Dict[str, Any], code_analysis: Dict[str, Any]) -> str:
    """Pick the file the fix should be written to: the uploaded file if it exists in the workspace."""
    project_path = state.get("project_path")
    project_name = state.get("project_name")
    if project_name and project_path and os.path.isfile(os.path.join(project_path, project_name)):
        return project_name
    files = (code_analysis.get("source_files") or []) + (code_analysis.get("test_files") or [])
    if files:
        return files[0]
    return project_name or "main.py"


def _compiles(code: str) -> bool:
    try:
        compile(code, "<fix>", "exec")
        return True
    except SyntaxError:
        return False


def _python_repair_fix(code: str, target_file: str, project_path: str) -> Dict[str, Any]:
    """Run the compile-and-run repair loop and package the result as a candidate fix."""
    repaired = repair_python_code(code, target_file, project_path)
    if not repaired["notes"]:
        return None
    explanation = "Automated repair: " + " ".join(repaired["notes"])
    fixed_code = repaired["fixed_code"]
    return {
        "explanation": explanation,
        "fixed_code": fixed_code,
        "changed_section": "\n".join(f"+ {n}" for n in repaired["notes"]),
        "patches": [{"file": target_file, "changes": fixed_code, "reason": explanation}],
        "repair_complete": repaired["runs_clean"],
        "engine": "rules",
    }


def _parse_llm_fix(raw: str) -> Dict[str, Any]:
    """Extract {"explanation", "fixed_code"} from an LLM reply (JSON, or a fenced code block)."""
    if not raw:
        return None
    text = raw.strip()
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        try:
            parsed = json.loads(m.group(0))
            if parsed.get("fixed_code"):
                code = parsed["fixed_code"]
                fence = re.match(r"^```\w*\n(.*?)\n?```\s*$", code.strip(), re.DOTALL)
                parsed["fixed_code"] = fence.group(1) if fence else code
                return parsed
        except Exception:
            pass
    fence = re.search(r"```\w*\n(.*?)```", text, re.DOTALL)
    if fence:
        return {"explanation": "Fix generated by the LLM.", "fixed_code": fence.group(1)}
    return None


def _strip_comments(code: str) -> str:
    return "\n".join(re.sub(r"\s*#.*$", "", l).rstrip() for l in code.splitlines() if l.strip() and not l.strip().startswith("#"))


def _wraps_errors(candidate: str, original: str) -> bool:
    """True if the candidate hides errors: a top-level try wrapper, or new broad excepts that just swallow."""
    first = next((l for l in candidate.splitlines() if l.strip() and not l.strip().startswith("#")), "")
    if first.startswith("try:"):
        return True
    swallow = r"except\s*(Exception)?\s*(as\s+\w+)?\s*:\s*\n\s*(pass|print\(|continue|return None)"
    return len(re.findall(swallow, candidate)) > len(re.findall(swallow, original))


def _llm_full_file_fix(code: str, target_file: str, language: str, error_output: str,
                       root_cause: Dict[str, Any], project_path: str, feedback: str) -> Dict[str, Any]:
    """
    Ask the LLM for the complete corrected file. For Python, run each candidate and feed any
    new error back for up to LLM_FIX_ROUNDS rounds; finish with the rule-based repair loop
    if something is still left. Returns None if the LLM gave nothing usable.
    """
    is_python = language == "python"
    history: List[str] = [feedback] if feedback else []
    explanations: List[str] = []
    current, output, best = code, error_output or "Program exited with an error.", None

    for round_no in range(1, LLM_FIX_ROUNDS + 1):
        prompt = FULL_FILE_FIX_USER_PROMPT.format(
            filename=target_file, language=language, source_code=current,
            error_output=(output or "")[-4000:],
            root_cause=json.dumps(root_cause or {}, indent=2)[:2000],
            history="\n".join(history) or "None (first attempt)",
        )
        parsed = _parse_llm_fix(call_llm(prompt, FULL_FILE_FIX_SYSTEM_PROMPT.format(language=language)))
        if not parsed:
            break  # LLM unavailable or unusable reply
        candidate = parsed["fixed_code"]

        if not is_python:
            best = candidate
            explanations.append(str(parsed.get("explanation", "")))
            break  # Java is compiled/run by the testing agent; the supervisor loop retries

        if not _compiles(candidate):
            history.append(f"Attempt {round_no}: your code did not compile. Return valid Python.")
            continue
        if _wraps_errors(candidate, current):
            history.append(f"Attempt {round_no}: you hid errors with try/except instead of fixing the cause. Fix the actual bug.")
            continue
        if _strip_comments(candidate) == _strip_comments(current) and round_no == 1:
            history.append(f"Attempt {round_no}: you only changed comments/whitespace. Fix the actual code.")
            continue

        explanations.append(str(parsed.get("explanation", "")).strip())
        current = best = candidate
        try:
            proc = run_python_file(candidate, target_file, project_path)
        except Exception as e:
            output = f"Execution failed: {e}"
            history.append(f"Attempt {round_no}: {output}")
            continue
        if proc.returncode == 0:
            break
        output = (proc.stdout + "\n" + proc.stderr).strip()
        history.append(f"Attempt {round_no}: still failing with:\n{output[-1500:]}")

    if best is None:
        return None

    explanation = "\n".join(e for e in explanations if e) or "Fix generated by the LLM."
    if is_python:
        # Rule-based loop as a safety net for anything the LLM left behind
        repaired = repair_python_code(best, target_file, project_path)
        if repaired["notes"]:
            explanation += "\nAutomated repair: " + " ".join(repaired["notes"])
        best = repaired["fixed_code"]

    return {
        "explanation": explanation,
        "fixed_code": best,
        "changed_section": explanation,
        "patches": [{"file": target_file, "changes": best, "reason": explanation}],
        "engine": "llm",
    }


def fallback_fix_generation(
    source_code: str,
    error_log: str,
    root_cause: Dict[str, Any],
    code_analysis: Dict[str, Any] = None
) -> Dict[str, Any]:
    """
    Rule-based fallback fix generator for arbitrary Python and Java errors.
    Generates real, targeted code modifications for common runtime/compiler exception patterns.
    """
    category = root_cause.get("bug_category", "")
    code_analysis = code_analysis or {}
    snippets = code_analysis.get("snippets", {})

    src_files = code_analysis.get("source_files", [])
    py_file = src_files[0] if src_files else (list(snippets.keys())[0] if snippets else "main.py")
    java_file = src_files[0] if src_files else (list(snippets.keys())[0] if snippets else "UserService.java")

    target_file = py_file if not (snippets and java_file in snippets and java_file.endswith(".java")) else java_file
    if snippets and target_file in snippets:
        source_code = snippets[target_file]

    fixed_code = source_code
    explanation = "Applied targeted code fix based on error analysis."
    changed_section = ""

    # 1. Java NullPointerException
    if "NullPointerException" in error_log or category == "NullPointerException":
        if "user.getName()" in source_code:
            fixed_code = source_code.replace(
                "return user.getName();",
                "if (user == null) {\n            return \"Guest\";\n        }\n        return user.getName();"
            )
            explanation = "Added null check guard for user object parameter."
        else:
            # General null guard insertion before method calls
            lines = source_code.splitlines()
            fixed_lines = []
            for line in lines:
                if "." in line and not line.strip().startswith("//") and not line.strip().startswith("import") and "package" not in line:
                    m = re.search(r'(\w+)\.([a-zA-Z0-9_]+)\(', line)
                    if m and m.group(1) not in ("System", "out", "this", "super", "Math", "String", "Objects"):
                        indent = " " * (len(line) - len(line.lstrip()))
                        fixed_lines.append(f"{indent}if ({m.group(1)} == null) return null;")
                fixed_lines.append(line)
            fixed_code = "\n".join(fixed_lines)
            explanation = "Inserted generic null reference guard check."

    # 2. Python ZeroDivisionError / Java ArithmeticException
    elif "ZeroDivisionError" in error_log or "/ by zero" in error_log or category in ("ZeroDivisionError", "ArithmeticException"):
        if "return total / count" in source_code:
            fixed_code = source_code.replace(
                "return total / count",
                "if not numbers or count == 0:\n        return 0.0\n    return total / count"
            )
            explanation = "Added explicit zero-count check before division."
        else:
            lines = source_code.splitlines()
            fixed_lines = []
            for line in lines:
                if "/" in line and not line.strip().startswith("#") and not line.strip().startswith("//"):
                    indent = " " * (len(line) - len(line.lstrip()))
                    # Match binary division: a / b
                    div_match = re.search(r'(\w+)\s*/\s*(\w+)', line)
                    if div_match:
                        num, denom = div_match.group(1), div_match.group(2)
                        fixed_lines.append(f"{indent}if {denom} == 0 or len({num} if '{num}' in locals() else []) == 0:")
                        fixed_lines.append(f"{indent}    return 0.0")
                fixed_lines.append(line)
            fixed_code = "\n".join(fixed_lines)
            explanation = "Inserted guard condition to prevent division by zero."

    # 3. IndexError / ArrayIndexOutOfBoundsException
    elif "IndexError" in error_log or "ArrayIndexOutOfBoundsException" in error_log or category in ("IndexError", "ArrayIndexOutOfBoundsException"):
        if "return items[2]" in source_code:
            fixed_code = source_code.replace(
                "return items[2]",
                "if len(items) <= 2:\n        return None\n    return items[2]"
            )
            explanation = "Added boundary check to verify list length before indexing."
        else:
            lines = source_code.splitlines()
            fixed_lines = []
            for line in lines:
                idx_match = re.search(r'(\w+)\[([^\]]+)\]', line)
                if idx_match and not line.strip().startswith("#"):
                    arr_var, idx_var = idx_match.group(1), idx_match.group(2)
                    indent = " " * (len(line) - len(line.lstrip()))
                    if idx_var.isdigit():
                        fixed_lines.append(f"{indent}if len({arr_var}) <= {idx_var}: return None")
                    else:
                        fixed_lines.append(f"{indent}if {idx_var} >= len({arr_var}): return None")
                fixed_lines.append(line)
            fixed_code = "\n".join(fixed_lines)
            explanation = "Added array/list index boundary validation."

    # 4. TypeError
    elif "TypeError" in error_log or category == "TypeError":
        lines = source_code.splitlines()
        fixed_lines = []
        for line in lines:
            if ("/" in line or "+" in line or "*" in line or "-" in line) and not line.strip().startswith("#"):
                # Convert string variables to numeric floats in arithmetic operations
                line_sub = re.sub(r'(?<!float\()([a-zA-Z_][a-zA-Z0-9_]*_percent|[a-zA-Z_][a-zA-Z0-9_]*_val)', r'float(\1)', line)
                fixed_lines.append(line_sub)
            else:
                fixed_lines.append(line)
        fixed_code = "\n".join(fixed_lines)
        if fixed_code == source_code:
            fixed_code = source_code.replace("discount", "float(discount)")
        explanation = "Cast parameter values to numeric types before performing arithmetic operations."

    # 5. KeyError
    elif "KeyError" in error_log or category == "KeyError":
        lines = source_code.splitlines()
        fixed_lines = []
        for line in lines:
            key_match = re.search(r'(\w+)\[["\']([^"\']+)["\'\]]', line)
            if key_match and not line.strip().startswith("#"):
                dict_var, key_name = key_match.group(1), key_match.group(2)
                line = line.replace(f'{dict_var}["{key_name}"]', f'{dict_var}.get("{key_name}", None)')
                line = line.replace(f"{dict_var}['{key_name}']", f'{dict_var}.get("{key_name}", None)')
            fixed_lines.append(line)
        fixed_code = "\n".join(fixed_lines)
        explanation = "Replaced direct dictionary indexing with dict.get() safe lookup."

    # 6. NameError
    elif "NameError" in error_log or category == "NameError":
        name_match = re.search(r"name '([^']+)' is not defined", error_log)
        var_name = name_match.group(1) if name_match else "undefined_var"
        lines = source_code.splitlines()
        fixed_lines = []
        inserted = False
        for line in lines:
            if var_name in line and not inserted and not line.strip().startswith("#"):
                indent = " " * (len(line) - len(line.lstrip()))
                fixed_lines.append(f"{indent}{var_name} = None")
                inserted = True
            fixed_lines.append(line)
        if not inserted:
            fixed_lines.insert(0, f"{var_name} = None")
        fixed_code = "\n".join(fixed_lines)
        explanation = f"Initialized undefined identifier '{var_name}' before usage."

    # 7. SyntaxError
    elif "SyntaxError" in error_log or category == "SyntaxError":
        lines = source_code.splitlines()
        fixed_lines = []
        for line in lines:
            stripped = line.strip()
            if any(stripped.startswith(kw) for kw in ("def ", "if ", "elif ", "else", "for ", "while ", "try", "except ")) and not stripped.endswith(":"):
                line = line + ":"
            fixed_lines.append(line)
        fixed_code = "\n".join(fixed_lines)
        explanation = "Added missing syntax colons to block headers."

    # 8. No rule matched. Never hide the error behind a try/except (or try/catch) wrapper:
    #    leave the code unchanged so verification reports the failure honestly.
    if fixed_code == source_code:
        explanation = "No automatic fix could be generated for this error (LLM unavailable and no rule matched)."

    patches = [{
        "file": target_file,
        "changes": fixed_code,
        "reason": explanation
    }]

    return {
        "explanation": explanation,
        "fixed_code": fixed_code,
        "changed_section": explanation,
        "patches": patches
    }


def generate_fix_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Fix Generation Agent Node for LangGraph.
    Receives state with source_code, root_cause, bug_investigation, and optional verification feedback.
    Returns candidate_fix dict with structured file patches.
    """
    source_code = state.get("source_code", "")
    error_log = state.get("error_log", "")
    root_cause = state.get("root_cause", {})
    bug_investigation = state.get("bug_investigation", {})
    verification_result = state.get("verification_result")
    code_analysis = state.get("code_analysis", {})

    exec_res = state.get("execution_result", {})
    if exec_res and not error_log:
        error_log = exec_res.get("stderr") or exec_res.get("output") or ""

    feedback = ""
    if verification_result and not verification_result.get("verified", False):
        feedback = f"Previous fix failed verification: {verification_result.get('reason', 'Tests failed')}"

    project_path = state.get("project_path")
    language = state.get("language", "python")
    is_python = language == "python"
    target_file = _resolve_target_file(state, code_analysis or {})
    file_code = source_code
    if not file_code and project_path and os.path.isfile(os.path.join(project_path, target_file)):
        with open(os.path.join(project_path, target_file), "r", encoding="utf-8") as f:
            file_code = f.read()

    # Primary engine: the LLM repairs the whole file, iterating on real run output
    if is_llm_available() and file_code:
        latest_output = ((state.get("test_results") or {}).get("output") if verification_result else None) or error_log
        llm_fix = _llm_full_file_fix(file_code, target_file, language, latest_output, root_cause,
                                     project_path, feedback)
        if llm_fix:
            return {"candidate_fix": llm_fix, "patches": llm_fix["patches"]}

    # Fallback for Python: iteratively compile/run/repair the actual file
    if is_python and file_code:
        repaired = _python_repair_fix(file_code, target_file, project_path)
        if repaired:
            return {"candidate_fix": repaired, "patches": repaired["patches"]}

    if is_llm_available() and not file_code:
        user_prompt = FIX_GENERATION_USER_PROMPT.format(
            source_code=source_code if source_code else f"Project snippets: {json.dumps(code_analysis.get('snippets', {}), indent=2)}",
            root_cause=json.dumps(root_cause, indent=2),
            bug_investigation=json.dumps(bug_investigation, indent=2),
            feedback=feedback if feedback else "None (First attempt)"
        )
        raw_response = call_llm(user_prompt, FIX_GENERATION_SYSTEM_PROMPT)

        if raw_response:
            try:
                cleaned = raw_response.strip()
                if cleaned.startswith("```json"):
                    cleaned = cleaned[7:]
                if cleaned.startswith("```"):
                    cleaned = cleaned[3:]
                if cleaned.endswith("```"):
                    cleaned = cleaned[:-3]
                
                parsed = json.loads(cleaned.strip())
                if "fixed_code" in parsed or "patches" in parsed:
                    if "patches" not in parsed:
                        main_file = state.get("project_name") or (code_analysis.get("source_files")[0] if code_analysis.get("source_files") else "main.py")
                        parsed["patches"] = [{
                            "file": main_file,
                            "changes": parsed.get("fixed_code", source_code),
                            "reason": parsed.get("explanation", "Fix generated by agent")
                        }]

                    # Check for unchanged fix: if generated code is identical to source_code, apply fallback fix
                    gen_code = parsed.get("fixed_code") or (parsed["patches"][0]["changes"] if parsed["patches"] else "")
                    if gen_code.strip() == source_code.strip() and error_log:
                        fallback_res = fallback_fix_generation(source_code, error_log, root_cause, code_analysis)
                        parsed["fixed_code"] = fallback_res["fixed_code"]
                        parsed["patches"] = fallback_res["patches"]
                        parsed["explanation"] = fallback_res["explanation"]

                    return {
                        "candidate_fix": parsed,
                        "patches": parsed.get("patches", [])
                    }
            except Exception:
                pass

    # Fallback mode
    result = fallback_fix_generation(source_code, error_log, root_cause, code_analysis)
    if file_code and len(result.get("patches", [])) == 1:
        result["patches"][0]["file"] = target_file
    return {
        "candidate_fix": result,
        "patches": result.get("patches", [])
    }

